### ISSUE TITLE
Help with W1L1 basicShapes example

### ISSUE THREAD

**Issue by abletsandtoast** [UoY-IM-PDM/PDM1-example-code#1]
Why does fill(255) on line 8 have one number but fill(0, 0, 255) on line 10 has 3?

**Comment by ace01603** [comment]
For any colour function (fill(), stroke(), background()), you can pass 1, 3, or 4 numbers. A single number will create a greyscale colour, with 0 meaning black, 255 meaning white, and any number between meaning a shade of grey. Passing 3 numbers will create an RGB colour. The first number is the amount of red, the second number is the amount of green, and the third number is the amount of blue. If you provide a fourth number, that will set the alpha channel (opacity) of the colour. The lower the alpha value, the more transparent the colour.

So, fill(0, 0, 255) specifies an RGB colour with no red, no green, and the maximum amount of blue.
